(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb ballebleu ballerouge  left right)
   (:init (room rooma)
          (room roomb)
          (ball ballebleu)
          (ball ballerouge)
          (at-robby rooma)
          (free left)
          (free right)
          (at ballebleu rooma)
          (at ballerouge rooma)
          (gripper left)
          (gripper right))
   (:goal (and (at ballerouge roomb)
               (at ballebleu roomb)
               )))
