(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb roomc roomd roome ball4 ball3 ball2 ball1 left right)
   (:init (room rooma)
          (room roomb)
	  (room roomc)
          (room roomd)
          (room roome)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (free right)
          (at ball4 roomb)
          (at ball3 roomb)
          (at ball2 rooma)
          (at ball1 rooma)
          (gripper left)
          (gripper right))
   (:goal (and (at ball4 roomd)
               (at ball3 roomc)
               (at ball2 roomc)
               (at ball1 roome))))
