(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb roomc roomd roome roomf roomg ball25 ball24 ball23 ball22 ball21 ball20 ball19 ball18 ball17 ball16 ball15 ball14 ball13 ball12 ball11 ball10 ball9 ball8 ball7 ball6 ball5 ball4 ball3 ball2 ball1 left right)
   (:init (room rooma)
          (room roomb)
	  (room roomc)
	  (room roomd)
	  (room roome)
	  (room roomf)
	  (room roomg)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
	  (ball ball5)
          (ball ball6)
          (ball ball7)
          (ball ball8)
	  (ball ball9)
          (ball ball18)
          (ball ball17)
          (ball ball16)
          (ball ball10)
	  (ball ball15)
          (ball ball13)
          (ball ball12)
          (ball ball11)
	  (ball ball14)
          (ball ball19)
          (ball ball22)
          (ball ball21)
	  (ball ball24)
          (ball ball23)
          (ball ball20)
          (ball ball25)
          (at-robby rooma)
          (free left)
          (free right)
          (at ball4 rooma)
          (at ball3 rooma)
          (at ball2 rooma)
          (at ball1 rooma)
          (at ball5 rooma)
          (at ball6 rooma)
          (at ball7 rooma)
          (at ball8 rooma)
          (at ball9 rooma)
          (at ball10 rooma)
          (at ball11 roomb)
          (at ball12 roomb)
          (at ball13 roomb)
          (at ball14 roomb)
          (at ball15 roomb)
          (at ball16 roomb)
          (at ball17 roomb)
          (at ball18 roomb)
          (at ball19 roomb)
          (at ball20 roomg)
	  (at ball24 roomg)
          (at ball23 roomg)
          (at ball22 roomg)
          (at ball21 roomg)
          (at ball25 roomg)
          (gripper left)
          (gripper right))
   (:goal (and (at ball4 roomb)
               (at ball3 roomb)
               (at ball2 roomb)
               (at ball1 roomb)
	       (at ball5 roomg)
               (at ball6 roomg)
               (at ball7 roomg)
               (at ball8 roomg)
	       (at ball9 roomg)
               (at ball13 roome)
               (at ball12 roomf)
               (at ball11 roomf)
	       (at ball14 roome)
               (at ball15 roome)
               (at ball16 roome)
               (at ball10 roome)
	       (at ball17 roomd)
               (at ball18 roomd)
               (at ball20 roomd)
               (at ball19 roomd)
	       (at ball24 rooma)
               (at ball23 rooma)
               (at ball22 rooma)
               (at ball21 rooma)
	       (at ball25 roomc))))
