(define (problem grounded_strips_psr_s2_n1_l2_f50-problem)
 (:domain grounded_strips_psr_s2_n1_l2_f50-domain)
 (:init (do_normal) (not_updated_cb1) (closed_sd2) (closed_sd1) (closed_cb1))
 (:goal (and (do_normal) (closed_cb1) (updated_cb1)))
)
