(define (problem grounded_strips_instance-problem)
 (:domain grounded_strips_instance-domain)
 (:init (settled_forks_1_) (queue_size_forks_1__zero) (queue_head_msg_forks_1__empty) (queue_tail_forks_1__qs_0) (queue_head_forks_1__qs_0) (settled_forks_0_) (queue_size_forks_0__zero) (queue_head_msg_forks_0__empty) (queue_tail_forks_0__qs_0) (queue_head_forks_0__qs_0) (at_process_philosopher_1_state_1) (pending_philosopher_1) (at_process_philosopher_0_state_1) (pending_philosopher_0))
 (:goal (and (blocked_philosopher_1) (blocked_philosopher_0)))
)
