[package]
name = "aries_planning_model"
version = "0.1.0"
authors = ["Arthur Bit-Monnot <arthur.bit-monnot@laas.fr>"]
edition = "2021"



[dependencies]
anyhow = "1.0"
clap = { version = "4.2.4", features = ["derive"] }
aries = { path = "../../solver" }
regex = "1.8.1"
itertools = "0.10.5"
