[package]
name = "coloring"
version = "0.1.0"
edition = "2024"

[dependencies]
aries = { path = "../../solver", features = ["cpu_cycles"] }
env_param = { version = "0.1.0", path = "../../env_param" }
