[package]
name = "minilp"
version = "0.2.2"
authors = ["Alexey Zatelepin <alex.zatelepin@gmail.com>"]
edition = "2024"
license = "Apache-2.0"
description = "A fast linear programming solver library."
repository = "https://github.com/ztlpn/minilp/"
readme = "README.md"
keywords = ["linear-programming", "optimization"]
categories = ["mathematics", "science"]

[dependencies]
sprs = { version = "0.9.4", default-features = false }
log = "0.4.32"

[dev-dependencies]
#ndarray = "0.17.2"
rand = { version = "0.7", features = ["small_rng"] }
rand_pcg = "0.2.1"
env_logger = "0.11.10"
