[[problems]]
name = "example-visitall-bool"
path = "examples/lprelax/instances/visitall-bool/problem.pddl"
max_depth = 4

[[problems]]
name = "ipc1998-gripper-round1-adl"
path = "planning/problems/upf/ipc1998-gripper-round1-adl/problem.pddl"
max_depth = 4

[[problems]]
name = "ipc1998-gripper-round1-strips"
path = "planning/problems/upf/ipc1998-gripper-round1-strips/problem.pddl"
max_depth = 4

[[problems]]
name = "ipc1998-movie-round1-strips"
path = "planning/problems/upf/ipc1998-movie-round1-strips/problem.pddl"
max_depth = 1

# [[problems]]
# name = "ipc1998-mystery-prime-round1-strips"
# path = "planning/problems/upf/ipc1998-mystery-prime-round1-strips/problem.pddl"
# max_depth = 3

# [[problems]]
# name = "ipc1998-mystery-prime-round2-strips"
# path = "planning/problems/upf/ipc1998-mystery-prime-round2-strips/problem.pddl"
# max_depth = 2

# [[problems]]
# name = "ipc1998-mystery-round1-strips"
# path = "planning/problems/upf/ipc1998-mystery-round1-strips/problem.pddl"
# max_depth = 3

[[problems]]
name = "ipc2000-blocks-strips-typed"
path = "planning/problems/upf/ipc2000-blocks-strips-typed/problem.pddl"
max_depth = 3

[[problems]]
name = "ipc2000-blocks-strips-untyped"
path = "planning/problems/upf/ipc2000-blocks-strips-untyped/problem.pddl"
max_depth = 3

[[problems]]
name = "ipc2000-elevator-strips-simple-typed"
path = "planning/problems/upf/ipc2000-elevator-strips-simple-typed/problem.pddl"
max_depth = 1

[[problems]]
name = "ipc2000-elevator-strips-simple-untyped"
path = "planning/problems/upf/ipc2000-elevator-strips-simple-untyped/problem.pddl"
max_depth = 1

[[problems]]
name = "ipc2002-depots-strips-automatic"
path = "planning/problems/upf/ipc2002-depots-strips-automatic/problem.pddl"
max_depth = 2

[[problems]]
name = "ipc2002-rovers-strips-automatic"
path = "planning/problems/upf/ipc2002-rovers-strips-automatic/problem.pddl"
max_depth = 2

[[problems]]
name = "ipc2002-satellite-strips-automatic"
path = "planning/problems/upf/ipc2002-satellite-strips-automatic/problem.pddl"
max_depth = 4

[[problems]]
name = "ipc2004-airport-nontemporal-strips"
path = "planning/problems/upf/ipc2004-airport-nontemporal-strips/problem.pddl"
max_depth = 1

[[problems]]
name = "ipc2004-pipesworld-no-tankage-nontemporal-strips"
path = "planning/problems/upf/ipc2004-pipesworld-no-tankage-nontemporal-strips/problem.pddl"
max_depth = 4

[[problems]]
name = "ipc2004-pipesworld-tankage-nontemporal-strips"
path = "planning/problems/upf/ipc2004-pipesworld-tankage-nontemporal-strips/problem.pddl"
max_depth = 4

[[problems]]
name = "ipc2004-promela-dining-philosophers-strips"
path = "planning/problems/upf/ipc2004-promela-dining-philosophers-strips/problem.pddl"
max_depth = 1

[[problems]]
name = "ipc2004-psr-small-strips"
path = "planning/problems/upf/ipc2004-psr-small-strips/problem.pddl"
max_depth = 2

[[problems]]
name = "ipc2004-satellite-strips"
path = "planning/problems/upf/ipc2004-satellite-strips/problem.pddl"
max_depth = 4

[[problems]]
name = "ipc2006-pathways-propositional-strips"
path = "planning/problems/upf/ipc2006-pathways-propositional-strips/problem.pddl"
max_depth = 1

[[problems]]
name = "ipc2006-pipesworld-propositional"
path = "planning/problems/upf/ipc2006-pipesworld-propositional/problem.pddl"
max_depth = 4

[[problems]]
name = "ipc2006-rovers-propositional"
path = "planning/problems/upf/ipc2006-rovers-propositional/problem.pddl"
max_depth = 2

[[problems]]
name = "ipc2006-rovers-propositional-strips"
path = "planning/problems/upf/ipc2006-rovers-propositional-strips/problem.pddl"
max_depth = 1

[[problems]]
name = "ipc2006-tpp-propositional"
path = "planning/problems/upf/ipc2006-tpp-propositional/problem.pddl"
max_depth = 2

[[problems]]
name = "ipc2006-tpp-propositional-strips"
path = "planning/problems/upf/ipc2006-tpp-propositional-strips/problem.pddl"
max_depth = 1
