[package]
authors = ["Selvakumar <selvakumar.h-s@laas.fr>"]
edition = "2021"
name = "aries_grpc_server"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow = { workspace = true }
aries = { path = "../../../solver" }
aries_planners = { path = "../../planners" }
aries_planning = { path = "../../planning" }
async-trait = { workspace = true }
clap = { workspace = true }
env_param = { path = "../../../env_param" }
fixedbitset = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
num-rational = { workspace = true }
prost = { workspace = true }
regex = { workspace = true }
streaming-iterator = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
unified_planning = { path = "../api" }
aries_plan_validator = { path = "../../../validator" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
async-stream = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic-build = { workspace = true }

# server binary
[[bin]]
name = "up-server"
path = "src/bin/server.rs"
